### PR TITLE
override join type to Arel::Nodes::OuterJoin in #make_polyamorous_lef…

### PR DESCRIPTION
**Pull request by neb2000**
…t_outer_joins

### CODE REVIEW

**Comment by jonatack** [comment]
Thanks @neb2000. Would you like to add a test? It seems we're missing one for this case.

**Comment by neb2000** [comment]
I've added a spec for this

**Comment by jonatack** [comment]
Thanks! :purple_heart:

**Comment by jonatack** [comment]
LGTM. Merging.

**Pull request merged**
